#!/bin/bash
#
# This script creates a virtualenv named 'env' and installs all
# python dependencies before activating the env and running Fermatum.
# If 'env' already exists, it is activated and Fermatum is started
# without any installations. Additionally, the PYTHONPATH environment
# variable is set properly before running Fermatum.
#
# python-qt and its dependencies will still need to be installed with
# your package manager.

if [ -e ./env/bin/activate ]; then
    source ./env/bin/activate
else
    virtualenv env
    source ./env/bin/activate
    python setup.py install
fi

export PYTHONPATH="/usr/local/lib/python2.7/site-packages:$PYTHONPATH"

./fermatum "$@"

deactivate
